# Cloud Build Configuration for WAOOAW Platform
# Updated for Mumbai (asia-south1) deployment
# Project: waooaw-oauth
# Artifact Registry: asia-south1-docker.pkg.dev/waooaw-oauth/waooaw-containers
# Last Updated: January 3, 2026

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Cloud Build substitutions - these ARE expanded in all contexts
substitutions:
  _BRANCH_NAME: 'main'
  _REGISTRY_HOSTNAME: 'asia-south1-docker.pkg.dev'  # Mumbai Artifact Registry
  _GCP_PROJECT: 'waooaw-oauth'
  _REGION: 'asia-south1'  # Mumbai region for deployment

steps:
  # Step 1: Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    waitFor: ['-']

  # Step 2: Build Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-frontend:latest'
      - '-f'
      - 'PlatformPortal/Dockerfile'
      - './PlatformPortal'
    waitFor: ['-']

  # Step 3 (revised): Wait for backend build - no test execution
  # Testing will be handled separately or in dev environment

  # Step 4: Push Backend Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-backend:latest'
    waitFor: ['build-backend']

  # Step 5: Push Frontend Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-frontend:latest'
    waitFor: ['build-frontend']

  # Step 6: Deploy Backend API to Cloud Run (Production - api.waooaw.com)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-api-production'
    args:
      - 'run'
      - 'deploy'
      - 'waooaw-api'
      - '--image=${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-backend:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'  # Scale to zero for cost optimization
      - '--max-instances=10'
      - '--port=8000'
      - '--set-env-vars=ENV=production,FRONTEND_URL=https://www.waooaw.com,GOOGLE_REDIRECT_URI=https://api.waooaw.com/auth/callback,CORS_ORIGINS="https://www.waooaw.com,https://pp.waooaw.com,https://dp.waooaw.com,https://yk.waooaw.com"'
      - '--set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest'
      - '--command=uvicorn'
      - '--args=app.main:app,--host,0.0.0.0,--port,8000'
      - '--project=${_GCP_PROJECT}'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    waitFor: ['push-backend']

  # Step 7: Deploy Platform Portal to Cloud Run (pp.waooaw.com)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-platform-portal'
    args:
      - 'run'
      - 'deploy'
      - 'waooaw-platform-portal'
      - '--image=${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-frontend:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--port=3000'
      - '--set-env-vars=ENV=production,BACKEND_URL=https://api.waooaw.com,DOMAIN=pp.waooaw.com'
      - '--project=${_GCP_PROJECT}'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    waitFor: ['push-frontend']

  # Step 8: Map domain mappings (optional - can also use Load Balancer)
  # NOTE: Domain mapping requires DNS already pointing to Cloud Run
  # For production, we use Load Balancer at 35.190.6.91 instead
  
  # Uncomment to enable direct domain mapping:
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: 'map-api-domain'
  #   args:
  #     - 'run'
  #     - 'domain-mappings'
  #     - 'create'
  #     - '--service=waooaw-api'
  #     - '--domain=api.waooaw.com'
  #     - '--region=${_REGION}'
  #     - '--platform=managed'
  #     - '--project=${_GCP_PROJECT}'
  #   waitFor: ['deploy-api-production']

# Images to push automatically
images:
  - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-backend:latest'
  - '${_REGISTRY_HOSTNAME}/${_GCP_PROJECT}/waooaw-containers/waooaw-frontend:latest'

# Build timeout
timeout: '1800s'

# Build tags for organization
tags:
  - 'waooaw-platform'
  - '${_BRANCH_NAME}'
