/**
 * OAuth Configuration
 * Google OAuth2 client IDs for different platforms
 * 
 * IMPORTANT: Replace placeholder values with actual client IDs from Google Cloud Console
 * 
 * Setup Instructions:
 * 1. Go to https://console.cloud.google.com/apis/credentials
 * 2. Create OAuth 2.0 Client IDs for:
 *    - iOS (bundle ID: com.waooaw.app)
 *    - Android (with SHA-1 fingerprint)
 *    - Web (for Expo standalone builds)
 * 3. For development, create an Expo client ID
 * 4. Replace values below with actual client IDs
 */

/**
 * Google OAuth2 Configuration
 */
export const GOOGLE_OAUTH_CONFIG = {
  /**
   * Expo Client ID - only needed for Expo Go development, not production builds
   */
  expoClientId: process.env.EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID || '',

  /**
   * iOS Client ID
   * Bundle ID: com.waooaw.app
   * Set via EAS secret: EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
   */
  iosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || '',

  /**
   * Android Client ID
   * Set via EAS secret: EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID
   * Get from: Google Cloud Console → APIs & Services → Credentials
   * → OAuth 2.0 Client IDs → Android (package: com.waooaw.app)
   * SHA-1 from EAS keystore: run `eas credentials -p android`
   *
   * Falls back to webClientId — expo-auth-session browser flow works
   * with just the web client on Android (no native redirect URI needed).
   */
  androidClientId:
    process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ||
    process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ||
    '',

  /**
   * Web Client ID
   * Same GOOGLE_CLIENT_ID used by cp.demo.waooaw.com backend
   * Set via EAS secret: EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
   */
  webClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || '',
};

/**
 * OAuth Scopes
 * Permissions requested from Google
 */
export const GOOGLE_OAUTH_SCOPES = [
  'openid',
  'profile',
  'email',
];

/**
 * OAuth Redirect URIs
 * Auto-generated by expo-auth-session
 */
export const OAUTH_REDIRECT_SCHEME = 'waooaw';

/**
 * Validate OAuth Configuration
 * Checks if all required client IDs are configured
 */
export const validateOAuthConfig = (): {
  isValid: boolean;
  missing: string[];
} => {
  const missing: string[] = [];

  // expoClientId is only needed for Expo Go development — skip in production builds
  const isExpoGo = process.env.EXPO_PUBLIC_APP_VARIANT === 'development' ||
    process.env.APP_ENV === 'development';

  if (isExpoGo && (!GOOGLE_OAUTH_CONFIG.expoClientId)) {
    missing.push('EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID');
  }

  // androidClientId falls back to webClientId — not required as a separate secret

  if (!GOOGLE_OAUTH_CONFIG.webClientId) {
    missing.push('EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID');
  }

  return {
    isValid: missing.length === 0,
    missing,
  };
};

/**
 * Get SHA-1 Fingerprint (for documentation)
 * 
 * Debug Keystore (Development):
 * ```bash
 * keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
 * ```
 * 
 * Release Keystore (Production):
 * ```bash
 * keytool -list -v -keystore /path/to/release.keystore -alias YOUR_ALIAS
 * ```
 * 
 * Look for SHA1 under "Certificate fingerprints"
 */
