/**
 * OAuth Configuration
 * Google OAuth2 client IDs for different platforms
 * 
 * IMPORTANT: Replace placeholder values with actual client IDs from Google Cloud Console
 * 
 * Setup Instructions:
 * 1. Go to https://console.cloud.google.com/apis/credentials
 * 2. Create OAuth 2.0 Client IDs for:
 *    - iOS (bundle ID: com.waooaw.app)
 *    - Android (with SHA-1 fingerprint)
 *    - Web (for Expo standalone builds)
 * 3. For development, create an Expo client ID
 * 4. Replace values below with actual client IDs
 */

/**
 * Google OAuth2 Configuration
 */
export const GOOGLE_OAUTH_CONFIG = {
  /**
   * Expo Client ID
   * Used during development with Expo Go
   * Format: *.apps.googleusercontent.com
   */
  expoClientId: process.env.EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID || 'YOUR_EXPO_CLIENT_ID.apps.googleusercontent.com',

  /**
   * iOS Client ID
   * Bundle ID must match: com.waooaw.app
   * Create in Google Cloud Console → Credentials → OAuth 2.0 Client IDs → iOS
   */
  iosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',

  /**
   * Android Client ID
   * Must use SHA-1 certificate fingerprint
   * Development: Use debug.keystore SHA-1
   * Production: Use release.keystore SHA-1
   */
  androidClientId: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID || 'YOUR_ANDROID_CLIENT_ID.apps.googleusercontent.com',

  /**
   * Web Client ID
   * Same as backend GOOGLE_CLIENT_ID
   * Used for ID token validation on backend
   */
  webClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || 'YOUR_WEB_CLIENT_ID.apps.googleusercontent.com',
};

/**
 * OAuth Scopes
 * Permissions requested from Google
 */
export const GOOGLE_OAUTH_SCOPES = [
  'openid',
  'profile',
  'email',
];

/**
 * OAuth Redirect URIs
 * Auto-generated by expo-auth-session
 */
export const OAUTH_REDIRECT_SCHEME = 'waooaw';

/**
 * Validate OAuth Configuration
 * Checks if all required client IDs are configured
 */
export const validateOAuthConfig = (): {
  isValid: boolean;
  missing: string[];
} => {
  const missing: string[] = [];

  if (!GOOGLE_OAUTH_CONFIG.expoClientId || GOOGLE_OAUTH_CONFIG.expoClientId.startsWith('YOUR_')) {
    missing.push('EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID');
  }

  if (!GOOGLE_OAUTH_CONFIG.iosClientId || GOOGLE_OAUTH_CONFIG.iosClientId.startsWith('YOUR_')) {
    missing.push('EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID');
  }

  if (!GOOGLE_OAUTH_CONFIG.androidClientId || GOOGLE_OAUTH_CONFIG.androidClientId.startsWith('YOUR_')) {
    missing.push('EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID');
  }

  if (!GOOGLE_OAUTH_CONFIG.webClientId || GOOGLE_OAUTH_CONFIG.webClientId.startsWith('YOUR_')) {
    missing.push('EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID');
  }

  return {
    isValid: missing.length === 0,
    missing,
  };
};

/**
 * Get SHA-1 Fingerprint (for documentation)
 * 
 * Debug Keystore (Development):
 * ```bash
 * keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
 * ```
 * 
 * Release Keystore (Production):
 * ```bash
 * keytool -list -v -keystore /path/to/release.keystore -alias YOUR_ALIAS
 * ```
 * 
 * Look for SHA1 under "Certificate fingerprints"
 */
