"""
Legacy Google auth module - DEPRECATED

This module contained duplicate/broken code generated by the coding agent.
The functionality has been moved to routes.py.

DO NOT USE THIS MODULE. It is kept only for backward compatibility
and excluded from coverage analysis.
"""

# pragma: no cover

            status_code=400,
            detail=f"Failed to handle Google callback: {str(e)}",
        )
