"""
Plant Gateway provider Pact verification.

Reads pact files generated by consumers (cp-backend, mobile-app) from
tests/contracts/pacts/ and verifies them against the Plant Gateway provider.
"""
import os
from pathlib import Path

import pytest

try:
    from pact import Verifier
    PACT_AVAILABLE = True
except ImportError:
    PACT_AVAILABLE = False

PACT_DIR = str(Path(__file__).resolve().parents[7] / "tests" / "contracts" / "pacts")
PROVIDER_BASE_URL = os.getenv("PLANT_GATEWAY_URL", "http://plant-gateway-test:8000")


@pytest.mark.contract
def test_plant_gateway_honours_cp_backend_pact():
    """Verify Plant Gateway fulfils the contract defined by cp-backend consumer."""
    if not PACT_AVAILABLE:
        pytest.skip("pact-python not installed")

    pact_files = list(Path(PACT_DIR).glob("cp-backend-plant-gateway.json"))
    if not pact_files:
        pytest.skip("No cp-backend consumer pact file found — run consumer tests first")

    verifier = Verifier(
        provider="plant-gateway",
        provider_base_url=PROVIDER_BASE_URL,
    )

    output, _ = verifier.verify_pacts(
        str(pact_files[0]),
        verbose=False,
    )
    assert output == 0, "Plant Gateway provider verification failed for cp-backend pact"


@pytest.mark.contract
def test_plant_gateway_honours_mobile_pact():
    """Verify Plant Gateway fulfils the contract defined by mobile-app consumer."""
    if not PACT_AVAILABLE:
        pytest.skip("pact-python not installed")

    pact_files = list(Path(PACT_DIR).glob("mobile-app-plant-gateway.json"))
    if not pact_files:
        pytest.skip("No mobile-app consumer pact file found — run mobile pact tests first")

    verifier = Verifier(
        provider="plant-gateway",
        provider_base_url=PROVIDER_BASE_URL,
    )

    output, _ = verifier.verify_pacts(
        str(pact_files[0]),
        verbose=False,
    )
    assert output == 0, "Plant Gateway provider verification failed for mobile-app pact"
