"""Plant Gateway provider Pact verification."""
import json
import os
import pytest


PACT_DIR = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "..", "..", "..", "..", "tests", "contracts", "pacts"
)


@pytest.mark.contract
class TestPlantGatewayProviderVerification:
    """Provider-side verification that Plant Gateway honours consumer contracts."""

    def _load_pacts(self):
        pacts = []
        if os.path.isdir(PACT_DIR):
            for fname in os.listdir(PACT_DIR):
                if fname.endswith(".json"):
                    with open(os.path.join(PACT_DIR, fname)) as f:
                        pacts.append(json.load(f))
        return pacts

    def test_provider_contract_structure_is_valid(self):
        """All pact files have valid structure."""
        pacts = self._load_pacts()
        # If no pacts yet, pass (pacts are generated by consumer tests)
        for pact in pacts:
            assert "consumer" in pact
            assert "provider" in pact
            assert "interactions" in pact
            for interaction in pact["interactions"]:
                assert "request" in interaction
                assert "response" in interaction

    def test_otp_start_route_exists(self):
        """Plant Gateway must expose POST /auth/otp/start."""
        required_routes = [
            ("POST", "/auth/otp/start"),
            ("POST", "/auth/otp/verify"),
            ("GET", "/agents"),
            ("POST", "/hire"),
        ]
        # Verify the routes are documented in our OpenAPI baseline
        openapi_path = os.path.join(
            os.path.dirname(__file__),
            "..", "..", "..", "..", "..", "..", "tests", "contracts", "plant-gateway-openapi.json"
        )
        if os.path.isfile(openapi_path):
            with open(openapi_path) as f:
                spec = json.load(f)
            paths = spec.get("paths", {})
            assert "/auth/otp/start" in paths
            assert "/agents" in paths
