name: Bug Report
description: Report a defect or issue in the platform
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Use this template to report defects, errors, or unexpected behavior in PP, CP, Plant, or Infrastructure.
        
        **Triage Process**: Testing Agent classifies severity → Developer fixes → Testing Agent validates

  - type: dropdown
    id: platform
    attributes:
      label: Platform Affected
      description: Where did the bug occur?
      options:
        - PP (Persona Portal)
        - CP (Customer Portal)
        - Plant (Agent Intelligence)
        - Gateway
        - Infrastructure
        - Multiple Platforms
      default: 0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - Production
        - Demo
        - UAT
        - Local Development
      default: 1
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Bug severity (Testing Agent charter classification)
      options:
        - P0 (Critical - Production down, data loss, security breach)
        - P1 (High - Major feature broken, >50% users affected)
        - P2 (Medium - Minor feature broken, workaround available)
        - P3 (Low - Cosmetic, edge case, <10% users affected)
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the issue
      placeholder: "OAuth login fails with 'Missing client_id' error on CP demo environment"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Navigate to https://cp.demo.waooaw.com
        2. Click "Sign in with Google" button
        3. Observe error in console: "Missing required parameter: client_id"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "User should be redirected to Google OAuth consent screen"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Error message displayed, login flow blocked"
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots / Logs
      description: Attach screenshots, error logs, or stack traces
      placeholder: |
        ```
        Error: Missing required parameter: client_id
        at OAuthClient.init (oauth.ts:45)
        at App.mount (App.tsx:23)
        ```
      render: markdown

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Browser, OS, user role, etc.
      placeholder: |
        - Browser: Chrome 120.0.6099.129
        - OS: macOS 14.2
        - User Role: Customer (trying to sign up)
        - Timestamp: 2026-01-18 14:30 UTC
      render: markdown

  - type: textarea
    id: impact
    attributes:
      label: Business Impact
      description: How many users affected? Revenue impact? Reputation risk?
      placeholder: |
        - **Users Affected**: 100% of new CP signups (estimated 20/day)
        - **Revenue Impact**: Potential $5000/day in lost trials
        - **Workaround**: None available

  - type: input
    id: related-pr
    attributes:
      label: Related PR/Deployment
      description: Was this introduced by a recent change? Link to PR or deployment run
      placeholder: "Introduced in PR #142 or deployment run #21109936716"

  - type: checkboxes
    id: regression-test
    attributes:
      label: Regression Test Required
      description: Should this bug have a regression test?
      options:
        - label: Yes - Add regression test to prevent recurrence
          required: false
