name: Implementation Task
description: Implement a designed component or feature
title: "[Implementation] "
labels: ["implementation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Implementation Task
        Use this template to track implementation of a designed component.
        
  - type: input
    id: component
    attributes:
      label: Component Name
      description: Name of the component being implemented
      placeholder: "e.g., MessageBus class, EventHandler, WowVision agent"
    validations:
      required: true
      
  - type: dropdown
    id: dimension
    attributes:
      label: Related Dimension
      description: Which of the 15 dimensions does this relate to?
      options:
        - "1 - Wake Protocol"
        - "2 - Context Management"
        - "3 - Identity System"
        - "4 - Hierarchy/RACI"
        - "5 - Collaboration"
        - "6 - Learning & Memory"
        - "7 - Communication Protocol"
        - "8 - Resource Management"
        - "9 - Trust & Reputation"
        - "10 - Error Handling"
        - "11 - Observability"
        - "12 - Security & Privacy"
        - "13 - Performance"
        - "14 - Testing"
        - "15 - Lifecycle"
        - "Multiple Dimensions"
        - "Infrastructure"
    validations:
      required: true
      
  - type: textarea
    id: scope
    attributes:
      label: Implementation Scope
      description: What will be implemented?
      placeholder: |
        Implement MessageBus class with:
        - publish() method
        - subscribe() method
        - Consumer group management
    validations:
      required: true
      
  - type: textarea
    id: design_ref
    attributes:
      label: Design Reference
      description: Link to design document or issue
      placeholder: |
        - Design: #2 [Design] Message Bus Architecture
        - Document: docs/MESSAGE_BUS_ARCHITECTURE.md
    validations:
      required: true
      
  - type: textarea
    id: tasks
    attributes:
      label: Implementation Tasks
      description: Checklist of tasks to complete
      placeholder: |
        - [ ] Create waooaw/messaging/message_bus.py
        - [ ] Implement MessageBus class
        - [ ] Implement publish() method
        - [ ] Implement subscribe() method
        - [ ] Write unit tests
        - [ ] Integration test with agent
        - [ ] Update documentation
    validations:
      required: true
      
  - type: input
    id: estimated_loc
    attributes:
      label: Estimated Lines of Code
      description: Rough estimate of LOC
      placeholder: "~600 LOC"
      
  - type: input
    id: estimated_time
    attributes:
      label: Estimated Time
      description: Time estimate for completion
      placeholder: "3-5 days"
      
  - type: input
    id: version
    attributes:
      label: Target Version
      description: Which version will include this implementation?
      placeholder: "v0.2.3"
      
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this is done?
      placeholder: |
        - [ ] All tests passing
        - [ ] Code reviewed
        - [ ] Documentation updated
        - [ ] Agent can send/receive messages
