name: User Story
description: Create a user story for feature development
title: "[STORY] "
labels: ["story", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template
        Use this template for user-facing features following INVEST principles (Independent, Negotiable, Valuable, Estimable, Small, Testable).
        
        **Typical Owner**: Business Analyst Agent (creates) → Developer (implements) → Testing Agent (validates)

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is this story for?
      options:
        - PP (Persona Portal)
        - CP (Customer Portal)
        - Plant (Agent Intelligence)
        - Gateway
      default: 0
    validations:
      required: true

  - type: input
    id: epic
    attributes:
      label: Related Epic
      description: Link to parent epic (issue number)
      placeholder: "#150"

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write the story in "As a... I want... So that..." format
      placeholder: |
        **As a** Content Marketing Agent  
        **I want to** receive real-time task notifications via message queue  
        **So that** I can respond to customer requests within 2 hours
      render: markdown
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define testable acceptance criteria (Given/When/Then format preferred)
      placeholder: |
        - [ ] Given agent is online, when task assigned, then notification received within 5 seconds
        - [ ] Given agent is offline, when task assigned, then notification queued for delivery on reconnect
        - [ ] Given notification received, when agent clicks, then task details displayed
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Story priority (aligned with BA Agent charter)
      options:
        - P0 (Critical - Core platform functionality)
        - P1 (High - Key differentiator)
        - P2 (Medium - UX enhancement)
        - P3 (Low - Nice to have)
      default: 1
    validations:
      required: true

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: Estimated complexity (Fibonacci scale)
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "?"
      default: 6

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Dependencies, APIs, data model impacts (for developers)
      placeholder: |
        **Dependencies**: RabbitMQ message queue (#166), Agent service (#152)
        **APIs Required**: POST /api/v1/notifications/subscribe
        **Data Model**: Add notifications table with agent_id, task_id, status
      render: markdown

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: What must be completed to close this story?
      value: |
        - [ ] Unit tests passing (80%+ coverage)
        - [ ] Integration tests passing
        - [ ] Documentation updated (user guide if user-facing)
        - [ ] Acceptance criteria validated
        - [ ] Code review completed
      render: markdown

  - type: checkboxes
    id: invest-checklist
    attributes:
      label: INVEST Principles
      description: Confirm story follows INVEST principles
      options:
        - label: Independent (can be implemented without other stories)
          required: false
        - label: Negotiable (details can be refined)
          required: false
        - label: Valuable (delivers user/business value)
          required: true
        - label: Estimable (complexity can be estimated)
          required: false
        - label: Small (can be completed in one sprint)
          required: false
        - label: Testable (acceptance criteria are clear)
          required: true
