module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: {
        jsx: 'react',
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
      },
      isolatedModules: true,
      diagnostics: false,
    }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|@react-navigation|expo|@expo|expo-.*|@unimodules|unimodules)/)',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/__tests__/hireWizardScreen.test.tsx',
    '<rootDir>/__tests__/hiredAgentsHooks.test.tsx',
    '<rootDir>/__tests__/useRazorpay.test.ts',
    '<rootDir>/__tests__/discoverScreen.test.tsx',
    '<rootDir>/__tests__/useGoogleAuth.test.ts',
    '<rootDir>/__tests__/coreScreens.test.tsx',
    '<rootDir>/__tests__/agentHooks.test.tsx',
    '<rootDir>/__tests__/OTPInput.test.tsx',
    '<rootDir>/__tests__/integration/auth.test.ts',
    '<rootDir>/__tests__/secureStorage.test.ts',
    '<rootDir>/__tests__/accessibility.test.ts',
    '<rootDir>/__tests__/navigation.test.ts',
    '<rootDir>/__tests__/theme.test.ts',
    '<rootDir>/__tests__/integration/api.test.ts',
    '<rootDir>/__tests__/api.config.test.ts',
    '<rootDir>/e2e/app-launch.test.js',
    '<rootDir>/__tests__/integration/fontLoading.test.ts',
    '<rootDir>/__tests__/razorpay.service.test.ts',
  ],
  testMatch: ['**/__tests__/**/*.(test|spec).(ts|tsx|js)', '**/?(*.)+(spec|test).(ts|tsx|js)'],
  collectCoverageFrom: [
    'src/services/**/*.{ts,tsx}',
    'src/lib/apiClient.ts',
    '!src/**/*.d.ts',
    '!src/**/*.stories.tsx',
    '!src/**/__tests__/**',
    '!src/services/index.ts',
    '!src/services/userDataService.ts',
    '!src/services/hiredAgents/**',
    '!src/services/voice/**',
    '!src/services/payment/**',
    '!src/services/analytics/**',
    '!src/services/monitoring/**',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '^react-native$': '<rootDir>/node_modules/react-native',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^\\.\\./\\.\\./src/(.*)$': '<rootDir>/src/$1',
    '^\\.\\./src/services/TokenManagerService$': '<rootDir>/src/services/tokenManager.service.ts',
    '^expo-constants$': '<rootDir>/__mocks__/expo-constants.js',
    '^expo-web-browser$': '<rootDir>/__mocks__/expo-web-browser.js',
    '^expo-auth-session/providers/google$': '<rootDir>/__mocks__/expo-auth-session/providers/google.js',
    '^expo-auth-session$': '<rootDir>/__mocks__/expo-auth-session.js',
    '^@expo-google-fonts/space-grotesk$': '<rootDir>/__mocks__/expo-google-fonts.js',
    '^@expo-google-fonts/outfit$': '<rootDir>/__mocks__/expo-google-fonts.js',
    '^@expo-google-fonts/inter$': '<rootDir>/__mocks__/expo-google-fonts.js',
  },
};
