"""
Tests for WowCache
Distributed caching and performance optimization specialist that
accelerates
agent operations through intelligent caching strategies. Provides multi-
level
cache hierarchy, smart invalidation, and hit rate optimization.

Generated by WowAgentFactory
Version: 0.4.3
Tier: 4
"""

import pytest
from unittest.mock import Mock
from typing import Dict, Any

from waooaw.agents.wowcache import WowCache
from waooaw.factory.interfaces.coe_interface import (
    WakeEvent,
    EventType,
    DecisionRequest,
    DecisionMethod,
    ActionContext,
    ActionStatus,
    TaskDefinition
)


# =============================================================================
# FIXTURES
# =============================================================================

@pytest.fixture
def agent():
    """Create agent instance for testing"""
    agent = WowCache()
    return agent


@pytest.fixture
def wake_event():
    """Create sample wake event"""
    return WakeEvent(
        event_type=EventType.INTERNAL_TRIGGER,
        pattern="cache.*",
        payload={"test": "data"},
        source="test_system",
        priority=5
    )


# =============================================================================
# INITIALIZATION TESTS
# =============================================================================

def test_agent_initialization(agent):
    """Test agent initializes correctly"""
    assert agent.coe_name == "WowCache"
    assert agent.display_name == "WowCache"
    assert agent.tier == 4
    assert agent.domain == "intelligence"
    assert agent.version == "0.4.3"


def test_agent_capabilities(agent):
    """Test agent has required capabilities"""
    expected_capabilities = {"analytics": ["usage_patterns", "cache_efficiency", "performance_metrics"], "caching": ["l1_cache", "l2_cache", "l3_cache", "distributed_cache"], "invalidation": ["pattern_based", "ttl_management", "lru_eviction", "dependency_tracking"], "performance": ["hit_rate_monitoring", "latency_optimization", "cache_warming", "prefetching"]}
    for category, caps in expected_capabilities.items():
        assert category in agent.capabilities


def test_agent_dependencies(agent):
    """Test agent dependencies are registered"""
    expected_deps = ["WowVisionPrime", "WowAgentFactory", "WowMemory"]
    for dep in expected_deps:
        assert dep in agent.dependencies


# =============================================================================
# WAKE PROTOCOL TESTS
# =============================================================================

def test_should_wake_with_matching_pattern(agent, wake_event):
    """Test agent wakes on matching event pattern"""
    result = agent.should_wake(wake_event)
    assert isinstance(result, bool)


def test_should_wake_with_non_matching_pattern(agent):
    """Test agent ignores non-matching patterns"""
    event = WakeEvent(
        event_type=EventType.EXTERNAL_REQUEST,
        pattern="unrelated.event.pattern",
        payload={},
        source="test",
        priority=1
    )
    result = agent.should_wake(event)
    assert isinstance(result, bool)


# =============================================================================
# DECISION MAKING TESTS
# =============================================================================

def test_make_decision(agent):
    """Test agent can make decisions"""
    request = DecisionRequest(
        context={"request": "test"},
        method=DecisionMethod.RULE_BASED,
        constraints={}
    )
    decision = agent.make_decision(request)
    assert decision is not None
    assert hasattr(decision, 'approved')
    assert hasattr(decision, 'reason')


# =============================================================================
# ACTION EXECUTION TESTS
# =============================================================================

def test_act(agent):
    """Test agent can execute actions"""
    context = ActionContext(
        action_name="test_action",
        parameters={"param": "value"},
        metadata={}
    )
    result = agent.act(context)
    assert result is not None
    assert hasattr(result, 'status')
    assert hasattr(result, 'message')


# =============================================================================
# TASK EXECUTION TESTS
# =============================================================================

@pytest.mark.asyncio
async def test_execute_task(agent):
    """Test agent can execute tasks"""
    task = TaskDefinition(
        task_id="test-task-001",
        task_type="test_task",
        parameters={"param": "value"},
        priority=5,
        timeout_seconds=60
    )
    result = await agent.execute_task(task)
    assert result is not None
    assert hasattr(result, 'status')
    assert hasattr(result, 'output')