#!/usr/bin/env python3
"""
code_agent.py

Autonomous Code Agent for WAOOAW
- Accepts a story/spec as input (via CLI or environment)
- (Next step) Calls LLM APIs to generate code
- (Next step) Writes code to repo, commits, and pushes branch

Usage:
  python scripts/code_agent.py --story "Implement user login API"
"""
import argparse
import sys


import os
import requests

def call_claude_45(story: str) -> str:
  """Call Claude Sonnet 4.5 API to generate code for the given story."""
  api_key = os.getenv("CLAUDE_API_KEY")
  if not api_key:
    print("[WARN] CLAUDE_API_KEY not set. Skipping Claude call.")
    return ""
  # Example endpoint and payload (replace with real endpoint)
  endpoint = "https://api.anthropic.com/v1/messages"
  prompt = f"""
You are a world-class Python developer.
Write production-grade code for the following story, strictly following:
- PEP8 formatting
- Black code style
- Type hints everywhere
- Google-style docstrings for all functions/classes
- 100% testable code (no dead code)
- No secrets or hardcoded credentials
- No TODOs or placeholders
- Only the code, no explanation
Story: {story}
"""
  headers = {"x-api-key": api_key, "content-type": "application/json"}
  payload = {
    "model": "claude-4.5-sonnet",
    "messages": [{"role": "user", "content": prompt}],
    "max_tokens": 2048
  }
  try:
    resp = requests.post(endpoint, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
  except Exception as e:
    print(f"[Claude] API error: {e}")
    return ""

def call_gpt_52(story: str) -> str:
  """Call ChatGPT 5.2 API to generate code for the given story."""
  api_key = os.getenv("OPENAI_API_KEY")
  if not api_key:
    print("[WARN] OPENAI_API_KEY not set. Skipping GPT call.")
    return ""
  endpoint = "https://api.openai.com/v1/chat/completions"
  prompt = f"""
You are a world-class Python developer.
Write production-grade code for the following story, strictly following:
- PEP8 formatting
- Black code style
- Type hints everywhere
- Google-style docstrings for all functions/classes
- 100% testable code (no dead code)
- No secrets or hardcoded credentials
- No TODOs or placeholders
- Only the code, no explanation
Story: {story}
"""
  headers = {"Authorization": f"Bearer {api_key}", "content-type": "application/json"}
  payload = {
    "model": "gpt-5.2",
    "messages": [{"role": "user", "content": prompt}],
    "max_tokens": 2048
  }
  try:
    resp = requests.post(endpoint, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
  except Exception as e:
    print(f"[GPT] API error: {e}")
    return ""

def main():
  parser = argparse.ArgumentParser(description="Autonomous Code Agent for WAOOAW")
  parser.add_argument('--story', type=str, required=True, help='Story or spec to implement')
  args = parser.parse_args()

  story = args.story
  print(f"[Code Agent] Received story: {story}")

  # Call Claude 4.5
  claude_code = call_claude_45(story)
  if claude_code:
    print("[Claude 4.5] Code generated.")
  else:
    print("[Claude 4.5] No code generated.")

  # Call GPT-5.2
  gpt_code = call_gpt_52(story)
  if gpt_code:
    print("[GPT-5.2] Code generated.")
  else:
    print("[GPT-5.2] No code generated.")

  # Prefer Claude, fallback to GPT
  code = claude_code.strip() or gpt_code.strip()
  if not code:
    print("[ERROR] No code generated by either LLM.")
    sys.exit(1)
  print("\n--- Generated Code ---\n")
  print(code)

  # Write code to file (example: backend/app/generated_code.py)
  output_path = os.getenv("CODE_AGENT_OUTPUT", "backend/app/generated_code.py")
  os.makedirs(os.path.dirname(output_path), exist_ok=True)
  with open(output_path, "w") as f:
    f.write(code)
  print(f"[Code Agent] Code written to {output_path}")

  # Git commit and push (assumes git is configured and branch is checked out)
  import subprocess
  branch_name = f"code-agent-{os.getpid()}"
  try:
    subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    subprocess.run(["git", "add", output_path], check=True)
    subprocess.run(["git", "commit", "-m", f"Code Agent: implement {story}"], check=True)
    subprocess.run(["git", "push", "-u", "origin", branch_name], check=True)
    print(f"[Code Agent] Branch pushed: {branch_name}")
  except Exception as e:
    print(f"[Code Agent] Git error: {e}")
    sys.exit(1)

  # TODO: Open or update PR (can be done via GitHub CLI or API)

if __name__ == "__main__":
    main()
