"""
Tests for WowScaling
Load balancing and auto-scaling specialist that ensures platform
scalability
and optimal resource utilization. Provides horizontal scaling, intelligent
load distribution, capacity planning, and auto-scaling policies.

Generated by WowAgentFactory
Version: 0.4.4
Tier: 6
"""

import pytest
from unittest.mock import Mock
from typing import Dict, Any

from waooaw.agents.wowscaling import WowScaling
from waooaw.factory.interfaces.coe_interface import (
    WakeEvent,
    EventType,
    DecisionRequest,
    DecisionMethod,
    ActionContext,
    ActionStatus,
    TaskDefinition
)


# =============================================================================
# FIXTURES
# =============================================================================

@pytest.fixture
def agent():
    """Create agent instance for testing"""
    agent = WowScaling()
    return agent


@pytest.fixture
def wake_event():
    """Create sample wake event"""
    return WakeEvent(
        event_type=EventType.INTERNAL_TRIGGER,
        pattern="scale.*",
        payload={"test": "data"},
        source="test_system",
        priority=5
    )


# =============================================================================
# INITIALIZATION TESTS
# =============================================================================

def test_agent_initialization(agent):
    """Test agent initializes correctly"""
    assert agent.coe_name == "WowScaling"
    assert agent.display_name == "WowScaling"
    assert agent.tier == 6
    assert agent.domain == "scale"
    assert agent.version == "0.4.4"


def test_agent_capabilities(agent):
    """Test agent has required capabilities"""
    expected_capabilities = {"capacity": ["capacity_planning", "resource_forecasting", "utilization_monitoring", "cost_optimization"], "load_balancing": ["round_robin", "least_connections", "weighted_distribution", "session_affinity"], "policies": ["threshold_based", "predictive_scaling", "schedule_based", "custom_metrics"], "scaling": ["horizontal_scaling", "vertical_scaling", "auto_scaling", "scale_to_zero"]}
    for category, caps in expected_capabilities.items():
        assert category in agent.capabilities


def test_agent_dependencies(agent):
    """Test agent dependencies are registered"""
    expected_deps = ["WowVisionPrime", "WowAgentFactory", "WowAnalytics"]
    for dep in expected_deps:
        assert dep in agent.dependencies


# =============================================================================
# WAKE PROTOCOL TESTS
# =============================================================================

def test_should_wake_with_matching_pattern(agent, wake_event):
    """Test agent wakes on matching event pattern"""
    result = agent.should_wake(wake_event)
    assert isinstance(result, bool)


def test_should_wake_with_non_matching_pattern(agent):
    """Test agent ignores non-matching patterns"""
    event = WakeEvent(
        event_type=EventType.EXTERNAL_REQUEST,
        pattern="unrelated.event.pattern",
        payload={},
        source="test",
        priority=1
    )
    result = agent.should_wake(event)
    assert isinstance(result, bool)


# =============================================================================
# DECISION MAKING TESTS
# =============================================================================

def test_make_decision(agent):
    """Test agent can make decisions"""
    request = DecisionRequest(
        context={"request": "test"},
        method=DecisionMethod.RULE_BASED,
        constraints={}
    )
    decision = agent.make_decision(request)
    assert decision is not None
    assert hasattr(decision, 'approved')
    assert hasattr(decision, 'reason')


# =============================================================================
# ACTION EXECUTION TESTS
# =============================================================================

def test_act(agent):
    """Test agent can execute actions"""
    context = ActionContext(
        action_name="test_action",
        parameters={"param": "value"},
        metadata={}
    )
    result = agent.act(context)
    assert result is not None
    assert hasattr(result, 'status')
    assert hasattr(result, 'message')


# =============================================================================
# TASK EXECUTION TESTS
# =============================================================================

@pytest.mark.asyncio
async def test_execute_task(agent):
    """Test agent can execute tasks"""
    task = TaskDefinition(
        task_id="test-task-001",
        task_type="test_task",
        parameters={"param": "value"},
        priority=5,
        timeout_seconds=60
    )
    result = await agent.execute_task(task)
    assert result is not None
    assert hasattr(result, 'status')
    assert hasattr(result, 'output')