"""
Skill Entity - Capability instance for Agents and JobRoles
Inherits from BaseEntity (7 sections)
"""

from sqlalchemy import Column, String, Text, Index
from sqlalchemy.dialects.postgresql import VECTOR
from pydantic import BaseModel, Field
from typing import Optional, List

from models.base_entity import BaseEntity


class Skill(BaseEntity):
    """
    Represents a capability that Agents and JobRoles possess.
    
    Inherits all 7 sections from BaseEntity.
    Adds skill-specific attributes (name, category, embeddings).
    
    Example:
        >>> skill = Skill(
        ...     name="Python 3.11",
        ...     description="Backend Python development",
        ...     category="technical",
        ...     governance_agent_id="genesis"
        ... )
        >>> skill.validate_self()  # L0/L1 checks
    
    Constraints:
        - name must be unique per industry
        - category must be one of: [technical, soft_skill, domain_expertise]
        - embedding_384 generated by ML service (MiniLM-384)
        - Genesis certification required before use
    """
    
    __tablename__ = "skill_entity"
    
    # Override entity_type to specifically identify as Skill
    entity_type = "Skill"
    
    # Skill-specific attributes
    name = Column(
        String(255),
        nullable=False,
        unique=True,
        doc="Skill name (e.g., 'Python', 'Project Management')"
    )
    
    description = Column(
        Text,
        nullable=False,
        doc="Detailed description of the skill"
    )
    
    category = Column(
        String(50),
        nullable=False,
        doc="Category (technical, soft_skill, domain_expertise, certification)"
    )
    
    embedding_384 = Column(
        VECTOR(384),
        nullable=True,
        doc="MiniLM-384 embedding for semantic search (pgvector)"
    )
    
    genesis_certification = Column(
        # JSON stored in custom_attributes
        doc="Certification details {certification_id, date, signature_hash}"
    )
    
    # Indexes for performance
    __table_args__ = (
        Index("ix_skill_name", "name"),
        Index("ix_skill_category", "category"),
        Index("ix_skill_embedding", "embedding_384", postgresql_using="ivfflat", postgresql_ops={"embedding_384": "vector_cosine_ops"}),
    )
