"""
Tests for Auth Middleware (GW-100)

NOTE: JWT keys are generated by conftest.py pytest_configure hook.
Keys are retrieved via pytest.config in test fixtures.
"""

import pytest
import jwt
import os
from datetime import datetime, timedelta, timezone
from fastapi import FastAPI, Request
from fastapi.testclient import TestClient
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

from middleware.auth import (
    AuthMiddleware,
    JWTClaims,
    extract_bearer_token,
    validate_jwt,
    get_current_user
)

# Get JWT settings from environment (set by conftest.py)
JWT_ISSUER = os.environ.get("JWT_ISSUER", "waooaw.com")
PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY")

# Private key will be accessed via environment variable (set by conftest pytest_configure)
def _get_private_key():
    """Get private key from environment (set by conftest)."""
    # Try environment variable first (most reliable)
    private_key = os.environ.get("TEST_JWT_PRIVATE_KEY")
    if private_key:
        return private_key
    
    # Fallback: try to import from conftest
    try:
        import src.gateway.middleware.tests.conftest as conf
        return getattr(conf, 'TEST_PRIVATE_KEY_PEM', None)
    except:
        return None


def create_test_jwt(
    user_id="user-123",
    email="test@waooaw.com",
    customer_id="cust-456",
    roles=None,
    governor_agent_id=None,
    trial_mode=False,
    trial_expires_at=None,
    exp_delta=timedelta(hours=1),
    iss="waooaw.com",
    include_required=True
):
    """
    Create test JWT with configurable claims.
    
    Args:
        user_id: User ID
        email: User email
        customer_id: Customer ID
        roles: List of roles (default: ["user"])
        governor_agent_id: Governor agent ID (optional)
        trial_mode: Trial mode flag
        trial_expires_at: Trial expiration (ISO 8601 string)
        exp_delta: Expiration delta from now
        iss: Issuer
        include_required: Whether to include required claims (for testing missing claims)
    
    Returns:
        JWT token string
    """
    if roles is None:
        roles = ["user"]
    
    now = datetime.now(timezone.utc)
    payload = {}
    
    if include_required:
        payload = {
            "user_id": user_id,
            "email": email,
            "customer_id": customer_id,
            "roles": roles,
            "iat": int(now.timestamp()),
            "exp": int((now + exp_delta).timestamp()),
            "iss": iss,
            "sub": user_id,
        }
    
    # Optional claims
    if governor_agent_id:
        payload["governor_agent_id"] = governor_agent_id
    if trial_mode:
        payload["trial_mode"] = trial_mode
    if trial_expires_at:
        payload["trial_expires_at"] = trial_expires_at
    
    private_key = _get_private_key()
    if not private_key:
        raise RuntimeError("Private key not available from conftest")
    
    return jwt.encode(payload, private_key, algorithm="RS256")


# Test FastAPI app
app = FastAPI()
app.add_middleware(AuthMiddleware)


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.get("/api/v1/test")
async def test_endpoint(request: Request):
    jwt_claims = getattr(request.state, "jwt", {})
    return {
        "user_id": getattr(request.state, "user_id", None),
        "email": jwt_claims.get("email") if isinstance(jwt_claims, dict) else getattr(jwt_claims, "email", None),
        "roles": getattr(request.state, "roles", []),
        "trial_mode": getattr(request.state, "trial_mode", False),
    }


client = TestClient(app)


# ==================== Helper Function Tests ====================

def test_extract_bearer_token_valid():
    """Test extracting token from valid Bearer header."""
    token = extract_bearer_token("Bearer abc123")
    assert token == "abc123"


def test_extract_bearer_token_invalid_format():
    """Test invalid Authorization header format."""
    assert extract_bearer_token("Token abc123") is None
    assert extract_bearer_token("Bearer") is None
    assert extract_bearer_token("Bearer abc 123") is None
    assert extract_bearer_token("abc123") is None


def test_extract_bearer_token_missing():
    """Test missing Authorization header."""
    assert extract_bearer_token(None) is None
    assert extract_bearer_token("") is None


# ==================== JWTClaims Tests ====================

def test_jwt_claims_valid():
    """Test JWTClaims initialization with valid payload."""
    payload = {
        "user_id": "user-123",
        "email": "test@waooaw.com",
        "customer_id": "cust-456",
        "roles": ["user", "agent_orchestrator"],
        "iat": 1705485600,
        "exp": 1705489200,
        "iss": "waooaw.com",
        "sub": "user-123",
        "trial_mode": False,
    }
    
    claims = JWTClaims(payload)
    
    assert claims.user_id == "user-123"
    assert claims.email == "test@waooaw.com"
    assert claims.customer_id == "cust-456"
    assert claims.roles == ["user", "agent_orchestrator"]
    assert claims.trial_mode is False
    assert claims.governor_agent_id is None


def test_jwt_claims_governor():
    """Test Governor detection."""
    payload = {
        "user_id": "user-gov",
        "email": "governor@waooaw.com",
        "customer_id": "cust-456",
        "roles": ["admin"],
        "governor_agent_id": "gov_001",
        "iat": 1705485600,
        "exp": 1705489200,
        "iss": "waooaw.com",
        "sub": "user-gov",
    }
    
    claims = JWTClaims(payload)
    
    assert claims.is_admin()
    assert claims.is_governor()
    assert claims.governor_agent_id == "gov_001"


def test_jwt_claims_trial_mode():
    """Test trial mode with expiration."""
    future = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
    
    payload = {
        "user_id": "user-trial",
        "email": "trial@waooaw.com",
        "customer_id": "cust-789",
        "roles": ["user"],
        "trial_mode": True,
        "trial_expires_at": future,
        "iat": 1705485600,
        "exp": 1705489200,
        "iss": "waooaw.com",
        "sub": "user-trial",
    }
    
    claims = JWTClaims(payload)
    
    assert claims.trial_mode is True
    assert claims.trial_expires_at == future
    assert not claims.is_trial_expired()


def test_jwt_claims_trial_expired():
    """Test expired trial detection."""
    past = (datetime.now(timezone.utc) - timedelta(days=1)).isoformat()
    
    payload = {
        "user_id": "user-expired",
        "email": "expired@waooaw.com",
        "customer_id": "cust-789",
        "roles": ["user"],
        "trial_mode": True,
        "trial_expires_at": past,
        "iat": 1705485600,
        "exp": 1705489200,
        "iss": "waooaw.com",
        "sub": "user-expired",
    }
    
    claims = JWTClaims(payload)
    assert claims.is_trial_expired()


def test_jwt_claims_missing_required():
    """Test missing required claims."""
    # Missing user_id
    with pytest.raises(ValueError, match="Missing required claim: user_id"):
        JWTClaims({"email": "test@waooaw.com", "roles": ["user"]})
    
    # Missing email
    with pytest.raises(ValueError, match="Missing required claim: email"):
        JWTClaims({"user_id": "user-123", "roles": ["user"]})
    
    # Missing roles
    with pytest.raises(ValueError, match="Missing required claim: roles"):
        JWTClaims({"user_id": "user-123", "email": "test@waooaw.com", "iat": 123, "exp": 456, "iss": "waooaw.com", "sub": "user-123"})


def test_jwt_claims_trial_mode_missing_expiration():
    """Test trial_mode requires trial_expires_at."""
    payload = {
        "user_id": "user-trial",
        "email": "trial@waooaw.com",
        "customer_id": "cust-789",
        "roles": ["user"],
        "trial_mode": True,
        # Missing trial_expires_at
        "iat": 1705485600,
        "exp": 1705489200,
        "iss": "waooaw.com",
        "sub": "user-trial",
    }
    
    with pytest.raises(ValueError, match="trial_expires_at required when trial_mode is true"):
        JWTClaims(payload)


# ==================== validate_jwt Tests ====================

def test_validate_jwt_valid():
    """Test validating a valid JWT."""
    token = create_test_jwt()
    claims = validate_jwt(token)
    
    assert claims.user_id == "user-123"
    assert claims.email == "test@waooaw.com"
    assert claims.roles == ["user"]


def test_validate_jwt_expired():
    """Test expired JWT raises ExpiredSignatureError."""
    token = create_test_jwt(exp_delta=timedelta(seconds=-10))  # Expired 10 seconds ago
    
    with pytest.raises(jwt.ExpiredSignatureError):
        validate_jwt(token)


def test_validate_jwt_invalid_signature():
    """Test invalid signature raises InvalidTokenError."""
    # Create token with different key
    other_private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )
    other_private_pem = other_private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    ).decode()
    
    payload = {
        "user_id": "user-123",
        "email": "test@waooaw.com",
        "customer_id": "cust-456",
        "roles": ["user"],
        "iat": int(datetime.now(timezone.utc).timestamp()),
        "exp": int((datetime.now(timezone.utc) + timedelta(hours=1)).timestamp()),
        "iss": "waooaw.com",
        "sub": "user-123",
    }
    
    token = jwt.encode(payload, other_private_pem, algorithm="RS256")
    
    with pytest.raises(jwt.InvalidTokenError):
        validate_jwt(token)


def test_validate_jwt_invalid_issuer():
    """Test invalid issuer raises InvalidTokenError."""
    token = create_test_jwt(iss="evil.com")
    
    with pytest.raises(jwt.InvalidTokenError):
        validate_jwt(token)


def test_validate_jwt_missing_required_claim():
    """Test missing required claim raises InvalidTokenError."""
    token = create_test_jwt(include_required=False)
    
    with pytest.raises(jwt.InvalidTokenError):
        validate_jwt(token)


# ==================== Middleware Integration Tests ====================

def test_middleware_valid_jwt():
    """Test middleware with valid JWT."""
    token = create_test_jwt()
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["user_id"] == "user-123"
    assert data["email"] == "test@waooaw.com"
    assert data["roles"] == ["user"]
    assert data["trial_mode"] is False


def test_middleware_trial_user():
    """Test middleware with trial user JWT."""
    future = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
    token = create_test_jwt(
        user_id="user-trial",
        email="trial@waooaw.com",
        trial_mode=True,
        trial_expires_at=future
    )
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["user_id"] == "user-trial"
    assert data["trial_mode"] is True


def test_middleware_governor():
    """Test middleware with Governor JWT."""
    token = create_test_jwt(
        user_id="user-gov",
        email="gov@waooaw.com",
        roles=["admin"],
        governor_agent_id="gov_001"
    )
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["user_id"] == "user-gov"
    assert "admin" in data["roles"]


def test_middleware_missing_authorization():
    """Test middleware with missing Authorization header."""
    response = client.get("/api/v1/test")
    
    assert response.status_code == 401
    data = response.json()
    assert data["type"] == "https://waooaw.com/errors/unauthorized"
    assert data["title"] == "Unauthorized"
    assert "Missing Authorization header" in data["detail"]
    assert response.headers["WWW-Authenticate"] == "Bearer"


def test_middleware_invalid_bearer_format():
    """Test middleware with invalid Bearer format."""
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": "Token abc123"}
    )
    
    assert response.status_code == 401
    data = response.json()
    assert data["type"] == "https://waooaw.com/errors/invalid-token-format"
    assert "Bearer <token>" in data["detail"]


def test_middleware_expired_jwt():
    """Test middleware with expired JWT."""
    token = create_test_jwt(exp_delta=timedelta(seconds=-10))
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 401
    data = response.json()
    assert data["type"] == "https://waooaw.com/errors/token-expired"
    assert data["title"] == "Token Expired"
    assert "expired" in data["detail"].lower()


def test_middleware_invalid_jwt():
    """Test middleware with invalid JWT."""
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": "Bearer invalid.jwt.token"}
    )
    
    assert response.status_code == 401
    data = response.json()
    assert data["type"] == "https://waooaw.com/errors/invalid-token"
    assert "validation failed" in data["detail"].lower()


def test_middleware_public_endpoint_no_auth():
    """Test public endpoint bypasses authentication."""
    response = client.get("/health")
    
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"


def test_middleware_public_endpoint_with_auth():
    """Test public endpoint works with authentication too."""
    token = create_test_jwt()
    
    response = client.get(
        "/health",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"


# ==================== Performance Tests ====================

def test_middleware_performance():
    """Test middleware overhead is <5ms per request."""
    import time
    
    token = create_test_jwt()
    iterations = 100
    
    start = time.time()
    for _ in range(iterations):
        response = client.get(
            "/api/v1/test",
            headers={"Authorization": f"Bearer {token}"}
        )
        assert response.status_code == 200
    
    elapsed = time.time() - start
    avg_time_ms = (elapsed / iterations) * 1000
    
    # Should be < 5ms per request (generous threshold for CI)
    assert avg_time_ms < 10, f"Average middleware overhead: {avg_time_ms:.2f}ms (expected < 10ms)"
    print(f"✓ Average middleware overhead: {avg_time_ms:.2f}ms")


# ==================== Edge Cases ====================

def test_middleware_multiple_roles():
    """Test JWT with multiple roles."""
    token = create_test_jwt(roles=["user", "agent_orchestrator", "infrastructure_engineer"])
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert len(data["roles"]) == 3
    assert "agent_orchestrator" in data["roles"]


def test_middleware_empty_customer_id():
    """Test JWT without customer_id (optional claim)."""
    token = create_test_jwt(customer_id=None)
    
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": f"Bearer {token}"}
    )
    
    assert response.status_code == 200


def test_middleware_malformed_jwt():
    """Test completely malformed JWT."""
    response = client.get(
        "/api/v1/test",
        headers={"Authorization": "Bearer not.even.close"}
    )
    
    assert response.status_code == 401
    data = response.json()
    assert data["status"] == 401


# ==================== Summary ====================

if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
